language: scala
scala:
- 2.11.11
jdk:
- oraclejdk8
before_script:
- sudo apt-get install openssl
- sudo apt-get install libapr1 libapr1-dev
- ./.travis/nsq/start_nsq.sh ./.travis/nsq
script:
- sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    tags: true
env:
  global:
  - secure: yFY+8B8yRrPr8A0dz0kivtwUTp3sJS592NV0k4tzAhnxvn1gdfYAUUe2pOUEfAkraXTOfqG8zuu3ahMDTLsG1ZlouCLJ7wV8k2huZC3v15lwNdSRgGKuXJ0C7IIfMijAyLH3ZxNW7GWKBkHu6Zikn2a5+Dd/fI2Q4q9yEV0pfgH6fK3Zq5rE5tpIMfbj7x+3IGn7e5wEo+oNJ3dovFDoPFl3NBzPDWqzesZI0wthY47/cQP6+vfkk28l1N4VmDo7uwDUTigQsIKaGG9LEOX4mvTx34Jo03GUfFVNyoh3Hje4xWshPlDeThy5qat8OETnDB364sL3pcBVa3W1eYj4gvo+gA23s1p6pLJIcyW8Nm6l4E1WCK1qtaBHahHUez3jyf/6m7JL3DWV6R8ytQyun+djWIXfp1/73hltyfeKG9G04TV+8L8ULTMYjiM2tMobGvaARKufUxIAJPXvauSslNo4FR/slzxavQ96nJTYsPyEKQaZAMYUdSt18GS0LAWoiUny8bQBuhPm0YJ7weQ3QfEAwzuFoTbcoeUI6whnvLSYmVRN4wD07D72Y1v4LPmBACXraSJbJvKFj+dmSgQNG/wfKGk+onDrUPGTKUOaR5fsijQhTryG482y88XQyOk17LCM9OWAFpoODj7jjKklEVxQKTqn4bX7CAyOsOkJTyg=
  - secure: CiwdhrcZULU2UWrQuHc076+gO1o2a8gefwH6XlPj9Ton2JGhwmx0iYMvU7OxwyZYsWD+prBMv+djdF3/BPYQBEEBp6CmRqnM+8UPAmMvU/cZOek735RjtE29UmrSnxk1gIY6nRO4pn3Nx6N89HAf0tAPY9bNw7C+/6ctW2uvVnJGr7I34vBnfNKOGDATC2Far/IyxO7W5I84lFs1sprrCvqxlyhDTue56H2GeOm2n0bZRGaJXyUYT/jaud6/FCS1TYtFFV4W4RHW4WMHRHyqSkxEIaFR1jTzHmB2zZVR/2m+sRLQdpDnseUk0cCA1Mhz/RaywHWEF0T0bbVJ6z/piEWjqVxy7NM7uuP8F/Z5zkYh5rOLXmQg72BvmuTbLWt+eSO2Ug8TY09l6ril+/7uElN00p4x2OJbxspytgmW7mWRZgCVPVBLdpfAC7xKjuDBx8o707unA12go8Nx3r2iLlwR1IBRQIJ3i0h6d/LbZamfr3RpnX4h1EPuhs2BAghtfmeZwU3hc0KKuMUFIozbVjEmgI67JJf0SsFABj18W0JaE/xt74CcX5G409fn3ZW/SxX2ACwYsnOq5y5dan0+iqB0aXaL49I/+OoyIfWXcDiwLVsSGb4UTIXDW56RY/jMseXecVlhQ62cNvaWigfxgx+CAP1UP249N7e0ydp4I6U=
  - secure: i6pyEfZfT3ymfIfCnAJta9V74dbJcRd6E3pWjqnfKpViEafk61zNfVTzkLW7iMUpYfsfbwY4F3zD6sreCvX41xviZiy687UoJyHNMde4GMbdPrsb1o+PJMNLL3RgBSa8V37ZwfSaGsgMztub19tgtrnpfC5XAqgBnIOLqFjQlHFzYtF/6XYUhToNrmcP9/JAkP11tBhQeKKdxFWJ/dJHSpni7f1PrTR+atjt1vhGYZ3NsWSh5XIC1B1O/JmaMZIdY8/VU4KgKpwYGHc1xJ7QLBifzIXdLeUN6FRre1ZelUVhjFrWnqU+wSMKlYLDoWmpueNH8A5zsdeQAfpjOiS9cD3y8TCE0/ubgJFQ35zWhwI+wBXnhJ1WbBVGseF4KH+dHQvVGX5FsHbMrM7inLkUsVMX4mlhLtES6looA9GjxLl00+4TxcVBm1vxOKZqI4xmorndCMNSjIroRHBOQ6570MB2JXPhtxPr0Nw3qoyiio+4vrGldt5ZMqO4mqsHJgKH4N/66swavLGC+zoB5UEuTo6scSzvik9kz+koC/ov/WZh7J/JEToedHfPL4OE6xDAh8IayRwqAmRLfdoSS5ndzwMt9L40iQyFRxfRUzTjJxYl6XxX9AOXp+q/1sswhRzHaHC7u2Odl5u84S4zFaZr1R5sQRJvlP3bdNn5hIFs+ZE=
  - SONA_USER=snowplow
